#!/usr/bin/env python3
"""Extract OUT data packets from a USBPcap capture and emit them as a C
header for verbatim replay from firmware.

Default source: button.pcap (the capture that includes real button events).
Default range: frames 1235-1387 (two full init+image rounds) plus the
single CONNECT packet at frame 7511.

Run from project root:
   python tools/extract_akp_init.py > deskpad-host/main/akp_replay.h
"""
import struct
import sys
from pathlib import Path

PCAP = Path(__file__).resolve().parent.parent / "button.pcap"
AKP_ADDR = 45  # AKP's device address in button.pcap (verify per-capture)
AKP_EP_OUT = 3

# (start, end) inclusive frame ranges to fully replay
FRAME_RANGES = [(1235, 1387)]   # init + 2 image-upload rounds
# Additional single frames to include (e.g. CONNECT)
INCLUDE_FRAMES = [7511]          # CRT\0\0CONNECT

CRT = b"CRT"


def label_for(idx: int, payload: bytes) -> str:
    if payload[:3] == CRT and len(payload) >= 12:
        # Take bytes 5..12, keep only ASCII letters to avoid encoding issues.
        raw = payload[5:12].decode("ascii", errors="ignore")
        tag = "".join(c for c in raw if c.isalpha())
        if tag:
            return f"akp_p{idx:02d}_{tag}"
    return f"akp_p{idx:02d}_data"


def in_ranges(fn: int) -> bool:
    if fn in INCLUDE_FRAMES:
        return True
    return any(s <= fn <= e for s, e in FRAME_RANGES)


def main() -> int:
    captured = []  # (frame_num, payload_bytes)
    max_target = max([e for _, e in FRAME_RANGES] + INCLUDE_FRAMES)

    with open(PCAP, "rb") as f:
        f.read(24)
        fn = 0
        while True:
            rec_hdr = f.read(16)
            if len(rec_hdr) < 16:
                break
            _, _, incl_len, _ = struct.unpack("<IIII", rec_hdr)
            rec_data = f.read(incl_len)
            fn += 1
            if fn > max_target:
                break
            if not in_ranges(fn) or len(rec_data) < 27:
                continue

            header_len = struct.unpack("<H", rec_data[:2])[0]
            device = struct.unpack("<H", rec_data[19:21])[0]
            endpoint = rec_data[21] & 0x7F
            direction = (rec_data[21] >> 7) & 1
            transfer = rec_data[22]

            if (device != AKP_ADDR or transfer != 1 or direction != 0
                    or endpoint != AKP_EP_OUT):
                continue

            payload = rec_data[header_len:]
            if len(payload) > 0:
                captured.append((fn, payload))

    print(f"// Auto-generated by tools/extract_akp_init.py from button.pcap")
    print(f"// Source: device address {AKP_ADDR}, EP 0x{AKP_EP_OUT:02x} OUT")
    print(f"// Frame ranges: {FRAME_RANGES}, plus singletons {INCLUDE_FRAMES}")
    print(f"// {len(captured)} OUT packets total.")
    print(f"#pragma once")
    print(f"#include <stddef.h>")
    print(f"#include <stdint.h>")
    print()

    for idx, (fn, data) in enumerate(captured):
        label = label_for(idx, data)
        print(f"// Frame {fn} — {len(data)} bytes")
        print(f"static const uint8_t {label}[] = {{")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
            print(f"    {chunk},")
        print(f"}};")
        print()

    print(f"typedef struct {{ const uint8_t *data; size_t len; const char *name; }} akp_init_pkt_t;")
    print()
    print(f"static const akp_init_pkt_t akp_init_sequence[] = {{")
    for idx, (fn, data) in enumerate(captured):
        label = label_for(idx, data)
        print(f'    {{ {label}, sizeof({label}), "{label}" }},')
    print(f"}};")
    print(f"#define AKP_INIT_SEQUENCE_LEN  {len(captured)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
